#端口号配置
server:
  port: 8089
#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue-books-project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 188309

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty

#jwt配置
jwt:
  secret: com.itmk
  #30分钟过期
  expiration: 1800000

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

#alipay配置
alipay:
  # 应用ID，您的APPID，收款账号既是您的APPID对应支付宝账号
  appId: 2021000119684415
  # 支付宝公私钥生成地址：https://miniu.alipay.com/keytool/create
  # 商户私钥，您的PKCS8格式RSA2私钥
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBnXDwlnuECZyirDg9UaE3ExojkAu6Annyw5/D014VOISKamiJkcYMcm9evYD6yfojbdpAZ58b0hEX+Izsxd5E34zogivMnBtnChKKkvG6qH/c/YO1uWquyAlP2o0FfYFL1ITYZEu+bWe3mZPeLxnL4XO6iZLe2RGx108jWhIB37+267Vx5BnkrSx9X02C7NrSQAa/FVKrWyhCXdx00x84dD/dgVF1GyM3p39EkaGplIMBmycKPvZWBPdu9aK/GZytBTnacYZ/jS4oU/4KHtqWNPIeIPA3fxj7p2F13zqzXKp+uYdibpFbiDo9DbT7vUjAM51eFOl7PSJqZ3nXCeIlAgMBAAECggEAKsRAF6IPbymcvTAF/nWItBthbIqC1AUtJ6TUelCromTblrA1fe7TYhgAF0p/3D/4gOgmM0n9fbh6W2ZvWVCQXjlEzRLmUMTRZdY09/Q0PlqKlegwJS3gvXrTV73M+hrHJrYgfyXYuCRxLGtIFu+Dm3nwLYRnKZCF/iAExK1bc7Jf4iTi3/MEUg0MDjhHUp5NAkTRUIoFsd8PUtAw7fra84Ph46XRtjjF2d7X+m9En+qW3xdYbux3r0uV9OZRZ9qPRuEwJ7qeqzoTRBBS3NWV3kcyumkm9WMKTdbu0cbyB5vA2F7MnfXUTOIgZ5aq9A9okxAJLBeozFaNxTP8QQGYAQKBgQC2nNXL99X0xeaTIxnXfmYhsoZjD6BeUnjEi3WKnIzHyke4YN0bUWGJOJ1qco7WTXdfwE2UEgA2A0PU+QGgKZ8WZbzR1oClIE/aQKeuN4cHPIGawbCfm/HJI1QfTEggG6JVSG1ZTBx7jDwXnDGtFFet4ZMxoz2pX4IY5093SPeJQQKBgQC1tDdhOia4DKuI1aBpStQzMqU8AnpHdMRyd41y64z73ZDzvtjOervTjGKc5yPb8ZMpAzHUbzyvIuMq+pc2+t2Z3cVW9PGoMWQtMNdSmlSMvvrVx4JjYJ51PrEPfAOYktRHJXGIAUQi2Pn1nvnt05Ma+4F+z/OCvI4errvvXVJb5QKBgQCx8rzoCPdGkf6xTNgmxPZTSfto1tZoc6dZp6h/zTPmkLg49LMhprkMFc5X55BHRq/X77XpX20zNRVJmOi7oTN0iOlp9cPgpU8LGEwOGfAL3itRmgM6VaVUYofcA+KY3zTeNDjSdreesTXxr/Q8fAFA4PsluLQis348NFOcos8MwQKBgB/yruYOdm5X8/UcMpcwy/ywg/L4MI3NzxidQqaZGfHS9ECXJsGvPMUmYtRZo6lxYUGNyT4jzNSyWqTc6KeHFl2Oa7stWCwNeyKi+skQT5trnOjnqlpUy6ervTAOywcRkfdscvjJ2DQUWGbCbAlP8QaGgC9O2u76vjZQ3MRqcSetAoGALJMEryHyNVtbJwBnZVxZMaXPfOtxNVqfzF8DBGzUb4Ed6U6E6GhMjE4W32T6wpFY7cslxCL9EyHjU/JuIgI71awJZJ97U7YZqhJJ9mdl/qcubw3ckcT5hWDTlvhAJTrbpxY99tH7CwJzj2tjIvT48ahD8LEecNDFZI+tsF3EleI=
  # 支付宝公钥，查看地址：https://openhome.alipay.com/platform/keyManage.htm
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxy8tml6X0nHZ6sPB6NRPi3gRVKdQlrXochQcaZKF2HZmZED07yQRFcofywwYIzsC6tBODdYWVL4q9NJqwZIbrBUcPGdCVYIqmk+vnsc1keLt0Nc4q3P/uzliblXknKCqemjKeGtssE6zWAEnsi2uCmeeqw/+2u2tvJD4uDke4Lrkjvd6VJNe+RdixUbtmkjejnnMtRpCoRZbmMX8e85E6gxp7rAlO+YdOSKPL4fqYxkckzQ5jA+orPxRWAVoi3C3cOqaTetFiUSpRyCLvPui3YY2/0hgKGGRh1Z4kNR2HLt2Cog0WLmRyvWUTVgSygM4dwaP9M0ZngwLJUszOQ8gJQIDAQAB
  # 页面跳转异步通知页面路径，需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notifyUrl: http://localhost:9528/#/payFine
  # 页面跳转同步通知页面路径，需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  returnUrl: http://localhost:9528/#/payFine
  # 签名方式
  signType: RSA2
  # 字符编码格式
  charset: utf-8
  # 支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

log4j:
  additivity:
    org:
      apache: true
  appender:
    file: org.apache.log4j.DailyRollingFileAppender
    file.DatePattern: '''.''yyyy-MM-dd-HH-mm'
    stdout: org.apache.log4j.ConsoleAppender
    stdout.layout: org.apache.log4j.PatternLayout
    stdout.layout.ConversionPattern: '%-5p %c{1}:%L - %m%n'
    stdout.threshold: INFO
  rootLogger: DEBUG,stdout,file



